version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.14.2
    steps:
      - checkout
      - node/install-packages
      - run:
          name: do tests
          command: npm run test

workflows:
  test:
    jobs:
      - test
