version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:18.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: do tests
          command: yarn test

workflows:
  test:
    jobs:
      - test
